### ISSUE TITLE
we shall pass

### ISSUE THREAD

**Issue by Retype5555** [glenn-sorrentino/gatekeepers.lol#1]
it's all just
your
opinion, man.
We've all got at least one.

**Comment by glenn-sorrentino** [comment]
should it include the title?

```
it's all just
your
opinion, man.
We've all got at least one.
we shall pass.
```

**Comment by Retype5555** [comment]
yessir

**Comment by glenn-sorrentino** [comment]
<img width="1115" alt="Screenshot 2023-10-08 at 3 46 17 PM" src="https://github.com/glenn-sorrentino/gatekeepers.lol/assets/28545431/a5ae8ff5-821c-4931-b7ac-f6285e779502">
